[0m15:58:34.960824 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024405379D50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024404E92D50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024405378D10>]}


============================== 15:58:34.960824 | f37d42de-8788-4c28-b788-cf8e95e601a5 ==============================
[0m15:58:34.960824 [info ] [MainThread]: Running with dbt=1.9.1
[0m15:58:34.960824 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\ha200\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:58:44.574513 [debug] [MainThread]: Starter project path: C:\Users\ha200\MyWork\Self-Study\study_dagster\Lib\site-packages\dbt\include\starter_project
[0m15:58:44.666661 [info ] [MainThread]: 
Your new dbt project "dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:58:44.666661 [info ] [MainThread]: Setting up your profile.
[0m15:58:47.607964 [debug] [MainThread]: Redshift adapter: Setting redshift_connector to ERROR
[0m15:58:47.607964 [debug] [MainThread]: Redshift adapter: Setting redshift_connector.core to ERROR
[0m15:59:34.961667 [info ] [MainThread]: Profile dbt_project written to C:\Users\ha200\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:59:34.972546 [debug] [MainThread]: Command `dbt init` succeeded at 15:59:34.972546 after 60.12 seconds
[0m15:59:34.973532 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002447ECCC410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024405373D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024405372C10>]}
[0m15:59:34.973532 [debug] [MainThread]: Flushing usage events
[0m15:59:36.006928 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:00:30.585957 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002144A6EB510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002144A6EA750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002144A6EA7D0>]}


============================== 16:00:30.585957 | cca55bea-95cc-4d23-a8b7-81f6b4637eeb ==============================
[0m16:00:30.585957 [info ] [MainThread]: Running with dbt=1.9.1
[0m16:00:30.585957 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\ha200\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:00:30.585957 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\ha200\MyWork\Self-Study\study_dagster\Project\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:00:30.585957 [debug] [MainThread]: Command `dbt run` failed at 16:00:30.585957 after 0.09 seconds
[0m16:00:30.585957 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002144408C410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002144A74AED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002144A6E3FD0>]}
[0m16:00:30.595289 [debug] [MainThread]: Flushing usage events
[0m16:00:31.664959 [debug] [MainThread]: An error was encountered while trying to flush usage events
